source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HRLog_Example', :exclusive => true do
  pod 'HRLog', :path => '../'
end

target 'HRLog_Tests', :exclusive => true do
  pod 'HRLog', :path => '../'

  
end
